---
all:
  children:
    llanelli:
      hosts:
        llanelli-file-server:
          ansible_host: 10.10.10.10
          server_role: file-server
          server_site: llanelli
        llanelli-developer-server:
          ansible_host: 10.10.10.11
          server_role: developer-server
          server_site: llanelli
        llanelli-web-server:
          ansible_host: 10.10.20.10
          ansible_host_public: 203.0.113.10
          server_role: web-server
          server_site: llanelli
        llanelli-dhcp-server:
          ansible_host: 10.10.10.12
          server_role: dhcp-server
          server_site: llanelli

    cardiff:
      hosts:
        cardiff-backup-server:
          ansible_host: 10.20.10.10
          server_role: backup-server
          server_site: cardiff
        cardiff-email-server:
          ansible_host: 10.20.10.11
          server_role: email-server
          server_site: cardiff
        cardiff-security-server:
          ansible_host: 10.20.10.12
          server_role: security-server
          server_site: cardiff
        cardiff-dhcp-server:
          ansible_host: 10.20.10.13
          server_role: dhcp-server
          server_site: cardiff

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/welsh-blanket-factory.pem
    ansible_python_interpreter: /usr/bin/python3
