site_name: cardiff
vpc_cidr: 10.20.0.0/16

subnets:
  private: 10.20.10.0/24
  public: 10.20.40.0/24
  dmz:
    - 10.20.20.0/25
    - 10.20.20.128/25
  guest: 10.20.30.0/24
  management: 10.20.254.0/28

peer_site_cidr: 10.10.0.0/16
peer_site_name: llanelli
