---
site_name: llanelli
vpc_cidr: 10.10.0.0/16

subnets:
  private: 10.10.10.0/24
  public: 10.10.20.0/24
  guest: 10.10.30.0/24
  management: 10.10.254.0/28

peer_site_cidr: 10.20.0.0/16
peer_site_name: cardiff
