site_name: llanelli
vpc_cidr: 10.10.0.0/16

subnets:
  private: 10.10.10.0/24
  public: 10.10.40.0/24
  dmz:
    - 10.10.20.0/25
    - 10.10.20.128/25
  guest: 10.10.30.0/24
  management: 10.10.254.0/28

peer_site_cidr: 10.20.0.0/16
peer_site_name: cardiff
